---
- hosts: target
  become: yes
  remote_user: ec2-user
  become_user: root

  vars:
    #Remove deprecation warning
    ansible_python_interpreter: auto_silent

  tasks:
  - name: Get IP4 address
    ipify_facts:
    register: public_ip
  - debug:
      msg: '{{ ipify_public_ip }}'

  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-1.8.0-openjdk-devel

      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started

  - name: Get first Jenkins password
    ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_first_pass

  - name: Jenkins temp creeds
      ansible.builtin.debug:
        msg: "{{ jenkins_first_pass.stdout }}"
        verbosity: 2

  - name: Install plugin
    jenkins_plugin:
      name: "{{ item }}"
      url_username: "admin"
      url_password: "{{ jenkins_first_pass.stdout }}"
      url: 'http://{{ ipify_public_ip }}:8080'
      timeout: 90
    with_items:
      - docker-workflow
      - aws-credentials
      - amazon-ecr
      - blueocean
      - terraform
